### ISSUE TITLE
cmd won't open

### ISSUE THREAD

**Issue by tomb56** [akioweh/EducationPerfected#39]
i tride to run v2 and the cmd flashes open and then closes. I don't know what's doing this, I'm doing everything the same as before. I've reinstaled puppeteer so its not that.

**Comment by KEN-2000l** [comment]
you are running from the start.cmd file?
add a second line in the file and write `pause` if it's not there already
then the window will stay open and you can see any error messages

possible problems:
firstly make sure that it is in the same folder as the index.js
node.js PATH problems where the command `node` is not found
