### ISSUE TITLE
Unable to start the script

### ISSUE THREAD

**Issue by botboy434** [akioweh/EducationPerfected#43]
Everything loads, the hot keys just don't work and nothing is in my console, I'm on Linux incase that has anything to do with it

**Comment by akioweh** [comment]
i have no idea please provide more info

**Comment by botboy434** [comment]
Will do soon, nothing gets posted to console, but puppeteer opens the chrome window, I've also checked the web console incase it's in there, and it wasn't

**Comment by akioweh** [comment]
i've never actually tested on linux because i do not have a suitable machine to test on
i theory it should work fine since node and puppeteer are platform independent... but i'm not sure

**Comment by botboy434** [comment]
There's nothing in console, and I can't get the hotkeys to work, this is really strange

**Comment by botboy434** [comment]
Tested on windows, still doesn't work, any insight?

**Comment by akioweh** [comment]
nope... i got no clue :(
try executing the script with different methods
and update the script with the newest version

**Comment by botboy434** [comment]
Finally got a result, every hotkey works, besides starting the loop, this is the error that I get:
Error: Error: failed to find element matching selector "#question-text"
    at ElementHandle.$eval (D:\EducationPerfected-2.1.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ElementHandle.js:147:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async answerLoop (D:\EducationPerfected-2.1.0\index2.js:179:36)

**Comment by akioweh** [comment]
seems like it can't find the question to read it now

**Comment by akioweh** [comment]
i have no idea why... the lastest version of the script works completely fine for me
try updating it if you haven't yet

also make sure you only press the alt + s hotkey on the task screen like this:
![image](https://user-images.githubusercontent.com/79527273/190559593-211a6c30-08e3-44a5-8544-84c9ac430ed8.png)

**Comment by akioweh** [comment]
if you press the hotkey in an incorrect screen it will log the error to console but should continue to work properly

**Comment by botboy434** [comment]
Ohhhhhh, your tasks are like that, that would explain it
nevermind thanks for the script however
