### ISSUE TITLE
Errors in code

### ISSUE THREAD

**Issue by StinkyGherkin77** [akioweh/EducationPerfected#44]
There seems to be errors in your code, so far I have found that the system doesn't know what puppeteer is, then if you try to fix that it doesn't know what puppeteer.;aunch is. Maybe have a look through your code and try to fix these errors.

**Comment by akioweh** [comment]
did you install puppeteer properly... read the readme

**Comment by StinkyGherkin77** [comment]
Yes i did read it and i did install it, and as i run it, it doesn't seem to work. It shows the errors in the popup window. also the start file doesn't work either and i try to do it manually and i still cant seem to find the right way to open it in cmd.

**Comment by StinkyGherkin77** [comment]
![Administrator_ C__WINDOWS_system32_cmd exe 6_09_2022 8_49_56 PM](https://user-images.githubusercontent.com/112943998/188616838-ce74be9e-9ba5-4880-9c6e-b826f056ad90.png)

**Comment by akioweh** [comment]
ah i think im stupid
i removed package.json from the repo... ill reupload that

**Comment by akioweh** [comment]
actually no that shouldnt matter
that error seems to be from trying to install puppeteer?

**Comment by akioweh** [comment]
seems like your npm installation is broken
try reinstalling npm
easiest way is to delete npm (from `%appdata%` location in windows explorer)
then run node.js installer to reinstall

**Comment by akioweh** [comment]
inactivity
