### ISSUE TITLE
Without Admin?

### ISSUE THREAD

**Issue by Neodyminus** [akioweh/EducationPerfected#46]
Hi, As you most likely know, many of us who use Education Perfected are on student laptops, those without admin rights/revoked/limited admin ability. I was wondering if there was any possibility of a system that didn't require administrator rights to set up. Most notably is a full installation of Node.js. (which can be circumvented by downloading the .zip version). 

Just wanted to say I really do love what you are/have been doing.

Thank you so so much for the hours you have saved me
And thank you in advance for your response
-Neo

**Comment by akioweh** [comment]
thanks for the support
i will try to add instructions for a more manual installation of require javascript stuffs that doesn't require root perms

**Comment by Neodyminus** [comment]
Thanks so much! Just a quick side-note, when I tried it out on a computer that had perms, the pop-up would auto close after 30 seconds, even after having logged into my account.

**Comment by anneeeeeeeeeeee** [comment]
> Thanks so much! Just a quick side-note, when I tried it out on a computer that had perms, the pop-up would auto close after 30 seconds, even after having logged into my account. Am I missing something?

Same thing happened to me.
