### ISSUE TITLE
Updated login issues

### ISSUE THREAD

**Issue by Dontmindthehacker** [akioweh/EducationPerfected#47]
This code worked perfectly until ep showed me a pop-up that said I needed to update. I updated it because ep does about 500 updates a day and it took me to a new login screen that did not auto login, even with google passwords. I tried to sign-in manually but it kicked me out and closed the window. I did manage to sign in manually with out the script running.
This is the new login page: 'https://iam.educationperfect.com/oauth2/authorize?client_id=53770139-f524-c00a-26fe-b950fb0fe91e&response_type=code&redirect_uri=https%3a%2f%2fauthentication.educationperfect.com%2foauth-redirect&scope=offline_access&state=eyJ0YXJnZXRfbGlua191cmkiOiJodHRwczovL2FwcC5lZHVjYXRpb25wZXJmZWN0LmNvbS9hcHAvbG9naW4%2fbG9naW5fYXR0ZW1wdD0xIiwicmZwIjoiY2ZFRFpBNGIrWHAwQlhTNDBtV0tMNm05R0FHZUh4TnlGODFMU01CQmJjRT0ifQ%3d%3d',
error page: https://app.educationperfect.com/app/login?login_attempt=1&auth_error=ERR_LOGIN_RFP_FAILURE&auth_error_correlation_id=8ef6648f-7bf9-447e-8746-c2cd1cbfcb1d

**Comment by Dontmindthehacker** [comment]
It seems to kick me out after a certain time.
command prompt error:
ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
    at C:\Users\----\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:298:24
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\----\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:294:16)
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\---\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:210:46)
    at ExecutionContext.evaluateHandle (C:\Users\----\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:158:107)
    at WaitTask.rerun (C:\Users\----\node_modules\puppeteer\lib\cjs\puppeteer\common\IsolatedWorld.js:473:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: ''
}

**Comment by akioweh** [comment]
ah looks like they changed the html n stuff the login page so the script cannot find the input boxes
should be easy to fix

also apparently EP had server side issues about logging in which should explain your failed manual attempts

**Comment by akioweh** [comment]
ok everything should be fixed now (i just changed the css selectors)

**Comment by Dontmindthehacker** [comment]
thanks
