### ISSUE TITLE
Tab closing almost instantly

### ISSUE THREAD

**Issue by anneeeeeeeeeeee** [akioweh/EducationPerfected#48]
says "TimeoutError: waiting for selector `#login-username` failed: timeout 30000ms exceeded". Tried removing '#login-username' from line 13 replacing it with my email and didn't work. I'm so sorry if I'm being stupid I truly know nothing about coding.

**Comment by akioweh** [comment]
update the script (re-copy-paste) from the source
EP changed their website so i had to update the css selectors
