### ISSUE TITLE
Mathletics task deleater?

### ISSUE THREAD

**Issue by Dontmindthehacker** [akioweh/EducationPerfected#49]
Hi, I was wondering if anyone with experience with tamper monkey could help me develop a Mathletics cheat code that deletes all your tasks and inserts the no task picture.

**Comment by akioweh** [comment]
i dont really know what mathletics is...

**Comment by Dontmindthehacker** [comment]
It's the most annoying way to learn math.
Go to https://login.mathletics.com and use my login
username: GIL10886
password: knock14

**Comment by Susmaster64** [comment]
ahh, good old mathletics, i don't know much about it (last time i used it was 6-7 years ago), but you could theoretically edit the client side HTML and make the page display the "no task" image, but that is useless cause its client sided. (unless you want to do what the kids call "some dank trolling" and pretend mathletics is broken and the teacher's feed is broken.

**Comment by DanielWilliams78** [comment]
I'd like to get to the bottom of that. But to say that I love math, I don't.

**Comment by NicholasBarrett98** [comment]
I'm just getting ready for the writing sample and your recommendations are very helpful to me. I am told that it is not difficult as many people used to think. But just in case, I found a ghostwriting service that will definitely be able to help. But I reckon that I can do it alone.

**Comment by akioweh** [comment]
idk wtf the last two comments are... bot adverts?
