### ISSUE TITLE
Chromium just crashes

### ISSUE THREAD

**Issue by HelloBello234** [akioweh/EducationPerfected#51]
Bro what does this mean 😭😭😭😭😭
<img width="715" alt="Screenshot 2022-10-27 212322" src="https://user-images.githubusercontent.com/110455010/198260331-cbcee273-69d8-4916-a0b2-433dc9466616.png">

**Comment by HelloBello234** [comment]
https://pastebin.pl/view/fdb858db

Thats the full error

**Comment by Tom2009-cmd** [comment]
wtf does this mean 
TimeoutError: Waiting for selector `#login-username` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (C:\Users\TomCa\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:64:32)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

**Comment by akioweh** [comment]
@Tom2009-cmd update the script (get newest from the file on github here)
ep changed css tags a while ago that makes auto login fail

**Comment by akioweh** [comment]
@HelloBello234 idk what you're doing... trying to run the script? looks like you are running a shell command with npm?
try just opening terminal in the folder where the script is saved and enter `node index.js`

**Comment by akioweh** [comment]
inactivity
