### ISSUE TITLE
Not detecting correct answers

### ISSUE THREAD

**Issue by Dontmindthehacker** [akioweh/EducationPerfected#52]
I have been using Education Perfected to answer other kinds of list tasks (not language) and some answers will not be detected.
Sometimes it will throw this err:
Error: Error: failed to find element matching selector "#question-text"
    at ElementHandle.$eval (C:\Users\chris\node_modules\puppeteer\lib\cjs\puppeteer\common\ElementHandle.js:147:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async answerLoop (C:\Users\chris\OneDrive\Documents\SoFTwAre\EPFARMER\index.js:180:36)

**Comment by Dontmindthehacker** [comment]
Also it sometimes will just get stuck and print "No answer found for question" over and over again untill I stop it, wait ten seconds, and restart.

**Comment by Dontmindthehacker** [comment]
never have had this problem with language tasks.

**Comment by Dontmindthehacker** [comment]
This is an average go at a task with 20 questions, it will get stuck on one:
Starting answerLoop.
answerLoop entered.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
===== Details after Incorrect Answer: =====
Detected Question:
 => A state of exhaustion caused by a lack of food and water.
Inputted Answer:
 => IDK

Modal Question:
 =>  
Modal Full Answer:
 =>  
Modal Cut Answer:
 =>
Modal Detected Answered:
 =>



No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
===== Details after Incorrect Answer: =====
Detected Question:
 => A state of exhaustion caused by a lack of food and water.
Inputted Answer:
 => IDK

Modal Question:
 =>  
Modal Full Answer:
 =>  
Modal Cut Answer:
 =>
Modal Detected Answered:
 =>



No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
===== Details after Incorrect Answer: =====
Detected Question:
 => A state of exhaustion caused by a lack of food and water.
Inputted Answer:
 => IDK

Modal Question:
 =>  
Modal Full Answer:
 =>  
Modal Cut Answer:
 =>
Modal Detected Answered:
 =>



No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
===== Details after Incorrect Answer: =====
Detected Question:
 => A state of exhaustion caused by a lack of food and water.
Inputted Answer:
 => IDK

Modal Question:
 =>  
Modal Full Answer:
 =>  
Modal Cut Answer:
 =>
Modal Detected Answered:
 =>



No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
===== Details after Incorrect Answer: =====
Detected Question:
 => A state of exhaustion caused by a lack of food and water.
Inputted Answer:
 => IDK

Modal Question:
 =>  
Modal Full Answer:
 =>  
Modal Cut Answer:
 =>
Modal Detected Answered:
 =>



No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
===== Details after Incorrect Answer: =====
Detected Question:
 => A state of exhaustion caused by a lack of food and water.
Inputted Answer:
 => IDK

Modal Question:
 =>  
Modal Full Answer:
 =>  
Modal Cut Answer:
 =>
Modal Detected Answered:
 =>



No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
No answer found for A state of exhaustion caused by a lack of food and water.
===== Details after Incorrect Answer: =====
Detected Question:
 => A state of exhaustion caused by a lack of food and water.
Inputted Answer:
 => IDK

Modal Question:
 =>  
Modal Full Answer:
 =>  
Modal Cut Answer:
 =>
Modal Detected Answered:
 =>



Error: Error: failed to find element matching selector "#question-text"
    at ElementHandle.$eval (C:\Users\chris\node_modules\puppeteer\lib\cjs\puppeteer\common\ElementHandle.js:147:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async answerLoop (C:\Users\chris\OneDrive\Documents\SoFTwAre\EPFARMER\index.js:180:36)

**Comment by akioweh** [comment]
it is only meant to work for language questions
other subjects or types of tasks have different formats and stuff that may break it

**Comment by Dontmindthehacker** [comment]
Ahh, I wondered
