### ISSUE TITLE
Code keeps exiting - 300ms exceeded after login failed

### ISSUE THREAD

**Issue by mattiechen688** [akioweh/EducationPerfected#53]
It does not type credentials. It opens chromium, and then it fails to type username and password. Then, when you log in manually, chromium closes after 30 seconds and in the terminal it shows an error:

TimeoutError: Waiting for selector '#login-username' failed: Waiting failed: 3000ms exceeded.

**Comment by akioweh** [comment]
update script (get the newest content of index.js on github here)

**Comment by mattiechen688** [comment]
`Where?

**Comment by akioweh** [comment]
same place/method you initially installed the script...
i update by editing the file
