### ISSUE TITLE
I dont have any translation options

### ISSUE THREAD

**Issue by Nomu55** [akioweh/EducationPerfected#55]
I'm using this to try and be the number 1 in my school. I'm not enrolled in any classess that offer translation tasks but I was hoping someone could let me join their class using a class code maybe?

**Comment by akioweh** [comment]
![image](https://user-images.githubusercontent.com/79527273/218078890-93fd381b-48d9-4c61-9248-9700958c5b3a.png)
try clicking this button on the home page, add languages, and browse the default content (there's tasks in the nested folders)
