### ISSUE TITLE
After starting up it just goes to the login page and crashes eventually

### ISSUE THREAD

**Issue by luffanji** [akioweh/EducationPerfected#56]
\Users\hansy\Downloads\EducationPerfected-2.1.0\EducationPerfected-2.1.0>node index.js
C:\Users\hansy\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:65
                this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
                               ^

TimeoutError: Waiting for selector `#login-username` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (C:\Users\hansy\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:65:32)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

C:\Users\hansy\Downloads\EducationPerfected-2.1.0\EducationPerfected-2.1.0>pause
Press any key to continue . . .

**Comment by luffanji** [comment]
whenever i click a key to continue the whole program just kills itself

**Comment by akioweh** [comment]
> whenever i click a key to continue the whole program just kills itself

yeah that's normal because after it crashes it doesn't immediately close the terminal until you press a key so you can actually read the error messages

As for the issue itself... update your script. EP changed css of the input boxes (a long time ago) so it can't find certain stuff

**Comment by luffanji** [comment]
wdym by update my script

**Comment by luffanji** [comment]
i have added the password and email

**Comment by luffanji** [comment]
but it still doesn't work

**Comment by akioweh** [comment]
![image](https://user-images.githubusercontent.com/79527273/223912351-61c9d8df-399e-4fec-aa71-47b5d97a9c9a.png)
like... i might've edited it so just copy paste it again
