### ISSUE TITLE
Log in with School account option?

### ISSUE THREAD

**Issue by sevrdq** [akioweh/EducationPerfected#61]
My school requires you to press the 'Sign in with school account (SSO)' button, is it possible to log in via that?

**Comment by akioweh** [comment]
![image](https://user-images.githubusercontent.com/79527273/223912554-9fc98ddc-fa44-462e-9ee2-6908625764cb.png)
delete those lines
basically removes auto credential filling so you can click the sso button

**Comment by sevrdq** [comment]
And this is on index file?

**Comment by akioweh** [comment]
if you just open the file and see, you'll see it...
(yes, this is in the only code file - index.js)
