### ISSUE TITLE
ran the code, installed puppeteer. the chrome page loaded and i logged in, yet alt s did nothing. the terminal window just said.ust said

### ISSUE THREAD

**Issue by V01D-W4LK3R** [akioweh/EducationPerfected#71]
C:\example >node index.js
Opening EP page...
Waiting for login page to load...
Filling in login details...
Waiting for home page to load...
EP Home page loaded; Logged in.

**Comment by Ethanjoyce2010** [comment]
open a (language) lesson???

**Comment by qmanstal** [comment]
open a lesson that has questions then it works
