### ISSUE TITLE
Need to get in contact with you immediately, You dont have any support on your readme

### ISSUE THREAD

**Issue by DamnUi** [akioweh/EducationPerfected#74]
Hi, im a python dev, i hate ep too so i tried to automate it on my side using python and i seem to be successful and after a lot of trying found a viable way to also automate audio tasks using google cloud api (which gives 300$ free credit at the start so basically free) but i need a javascript dev with experince in this to help me out, if anyone is down or your down please get in contact with me on discord or here

discord - Nonja.

**Comment by akioweh** [comment]
im no javascript dev; this script is very simple and about as much as i can do.
I however believe that we don't need to do convoluted audio processing and all that; we can probably extract audio task data from the web app framework. I just don't know enough about web tool stacks to do that. If you have the energy you can try. I remember that EP uses Angular?
